function cekKhodam() {
    const nama = document.getElementById("nameInput").value;
    const khodams = [
        { name: "Harimau Putih", meaning: "Kamu kuat dan berani seperti harimau, karena pendahulumu mewariskan kekuatan besar padamu." },
        { name: "Lampu Tertidur", meaning: "Terlihat ngantuk tapi selalu memberikan cahaya yang hangat" },
        { name: "Panda Ompong", meaning: "Kamu menggemaskan dan selalu berhasil membuat orang tersenyum dengan keanehanmu." },
        { name: "Bebek Karet", meaning: "Kamu selalu tenang dan ceria, mampu menghadapi gelombang masalah dengan senyum." },
        { name: "Ninja Turtle", meaning: "Kamu lincah dan tangguh, siap melindungi yang lemah dengan kekuatan tempurmu." },
        { name: "Kucing Kulkas", meaning: "Kamu misterius dan selalu ada di tempat-tempat yang tak terduga." },
        { name: "Sabun Wangi", meaning: "Kamu selalu membawa keharuman dan kesegaran di mana pun kamu berada." },
        { name: "Semut Kecil", meaning: "Kamu pekerja keras dan selalu bisa diandalkan dalam situasi apa pun." },
        { name: "Moge Suzuki", meaning: "Kamu cepat dan penuh gaya, selalu menjadi pusat perhatian di jalanan." },
        { name: "Cupcake Pelangi", meaning: "Kamu manis dan penuh warna, selalu membawa kebahagiaan dan keceriaan." },
        { name: "Robot Mini", meaning: "Kamu canggih dan selalu siap membantu dengan kecerdasan teknologi tinggi." },
        { name: "Ikan Terbang", meaning: "Kamu unik dan penuh kejutan, selalu melampaui batasan yang ada." },
        { name: "Ayam Goreng", meaning: "Kamu selalu disukai dan dinanti oleh banyak orang, penuh kelezatan dalam setiap langkahmu." },
        { name: "Kecoa Terbang", meaning: "Kamu selalu mengagetkan dan bikin heboh seisi ruangan." },
        { name: "Kambing Ngebor", meaning: "Kamu unik dan selalu bikin orang tertawa dengan tingkah lakumu yang aneh." },
        { name: "Kerupuk Renyah", meaning: "Kamu selalu bikin suasana jadi lebih seru dan nikmat." },
        { name: "Celengan Babi", meaning: "Kamu selalu menyimpan kejutan di dalam dirimu." },
        { name: "Lemari Tua", meaning: "Kamu penuh dengan cerita dan kenangan masa lalu." },
        { name: "Kopi Susu", meaning: "Kamu manis dan selalu bikin semangat orang-orang di sekitarmu." },
        { name: "Sapu Lidi", meaning: "Kamu kuat dan selalu bisa diandalkan untuk membersihkan masalah." },
        { name: "Kuda Lumping", meaning: "Kamu penuh semangat dan selalu tampil beda di setiap kesempatan." },
        { name: "Sepatu Roda", meaning: "Kamu cepat dan lincah, selalu bergerak ke depan dengan penuh gaya." },
        { name: "Bola Pingpong", meaning: "Kamu ringan dan selalu bikin permainan jadi lebih seru." },
        { name: "Lumba-lumba", meaning: "Kamu pintar dan selalu membawa keceriaan di lautan kehidupan." },
        { name: "Kucing Gemuk", meaning: "Kamu santai dan selalu bikin orang tersenyum dengan kelucuanmu." },
        { name: "Iguana Pink", meaning: "Kamu eksotis dan selalu menarik perhatian dengan warnamu yang unik." },
        { name: "Bantal Guling", meaning: "Kamu nyaman dan selalu dibutuhkan saat waktu istirahat." },
        { name: "Komputer Jadul", meaning: "Kamu klasik dan penuh dengan pengetahuan di dalam dirimu." },
        { name: "Kasur Empuk", meaning: "Kamu selalu memberikan kenyamanan dan ketenangan." },
        { name: "Bola Bekel", meaning: "Kamu kecil tapi selalu memberikan kebahagiaan di setiap permainan." },
        { name: "Es Krim Pelangi", meaning: "Kamu manis dan penuh warna, selalu menyegarkan hari-hari." },
        { name: "Biskuit Coklat", meaning: "Kamu selalu bikin ketagihan dengan kelezatanmu yang tak tertahankan." },
        { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan kelezatanmu yang khas." },
        { name: "Roti Bakar", meaning: "Kamu sederhana tapi selalu bikin orang merasa nyaman." },
        { name: "Sepeda Ontel", meaning: "Kamu klasik dan selalu memberikan kesenangan di setiap perjalanan." },
        { name: "Sate Kambing", meaning: "Kamu gurih dan selalu jadi favorit di setiap kesempatan." },
        { name: "Kue Cubit", meaning: "Kamu kecil tapi selalu bikin orang bahagia dengan rasamu yang enak." },
        { name: "Bakso Urat", meaning: "Kamu kuat dan selalu memberikan kenikmatan di setiap gigitan." },
        { name: "Es Kelapa", meaning: "Kamu segar dan selalu bikin adem di saat-saat panas." },
        { name: "Siomay Bandung", meaning: "Kamu selalu bikin ketagihan dengan rasa khasmu yang lezat." },
        { name: "Bajigur Hangat", meaning: "Kamu selalu bikin suasana jadi hangat dan nyaman." },
        { name: "Martabak Manis", meaning: "Kamu penuh kejutan dengan isi yang manis dan nikmat." },
        { name: "Permen Karet", meaning: "Kamu selalu bikin suasana jadi lebih ceria dengan kenikmatanmu yang kenyal." },
        { name: "Pisang Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Telur Dadar", meaning: "Kamu sederhana tapi selalu bikin orang puas dengan kelezatanmu." },
        { name: "Es Buah", meaning: "Kamu segar dan penuh warna, selalu bikin hari jadi lebih ceria." },
        { name: "Mie Goreng", meaning: "Kamu selalu bikin kenyang dan puas dengan rasamu yang lezat." },
        { name: "Puding Coklat", meaning: "Kamu manis dan selalu bikin suasana jadi lebih nyaman." },
        { name: "Gulai Kambing", meaning: "Kamu kaya rasa dan selalu bikin orang ketagihan dengan kelezatanmu." },
        { name: "Kue Nastar", meaning: "Kamu selalu hadir di saat-saat spesial dengan rasa yang manis dan enak." },
        { name: "Krupuk Ikan", meaning: "Kamu renyah dan selalu bikin suasana jadi lebih seru." },
        { name: "Es Teler", meaning: "Kamu segar dan penuh kejutan dengan campuran rasa yang enak." },
        { name: "Rujak Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih hidup dengan rasamu yang pedas dan manis." },
        { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Tahu Bulat", meaning: "Kamu selalu hadir di momen-momen yang pas dengan rasa yang enak." },
        { name: "Keripik Singkong", meaning: "Kamu renyah dan selalu bikin suasana jadi lebih seru." },
        { name: "Kacang Goreng", meaning: "Kamu selalu jadi camilan favorit di setiap kesempatan." },
        { name: "Tongseng Sapi", meaning: "Kamu kaya rasa dan selalu bikin orang ketagihan dengan kelezatanmu." },
        { name: "Sate Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang lezat." },
        { name: "Nasi Uduk", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Cendol Dawet", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Onde-onde", meaning: "Kamu selalu hadir di saat-saat spesial dengan rasa yang manis dan enak." },
        { name: "Kolak Pisang", meaning: "Kamu manis dan selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Macan Kumbang", meaning: "Kamu misterius dan kuat, seperti macan yang jarang terlihat tapi selalu waspada." },
        { name: "Kuda Emas", meaning: "Kamu berharga dan kuat, siap untuk berlari menuju kesuksesan." },
        { name: "Elang Biru", meaning: "Kamu memiliki visi yang tajam dan dapat melihat peluang dari jauh." },
        { name: "Indomie Goreng", meaning: "Selalu bikin kenyang dan bahagia" },
        { name: "Es Krim Meleleh", meaning: "Selalu mencairkan suasana" },
        { name: "Rendang Sapi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang lezat." },
        { name: "Ayam Bakar", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Ikan Bakar", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Liwet", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Gado-gado", meaning: "Kamu selalu bikin suasana jadi lebih segar dengan campuran rasa yang enak." },
        { name: "Sop Buntut", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Nasi Goreng", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Sate Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang lezat." },
        { name: "Bakso Sapi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang lezat." },
        { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang lezat." },
        { name: "Es Doger", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Serabi Bandung", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Ketoprak Jakarta", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Cilok Bandung", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa kenyalmu yang enak." },
        { name: "Pecel Lele", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Es Kopyor", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Sop Kaki Kambing", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Campur Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." },
        { name: "Mie Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Kerak Telor", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Kucing", meaning: "Kamu selalu bikin kenyang dan puas dengan porsi kecilmu yang enak." },
        { name: "Soto Mie", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Sop Iga", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Klepon", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa manismu yang enak." },
        { name: "Bakwan Jagung", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Gudeg", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Sop Buntut", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Nasi Lemak", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Tahu Gejrot", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa asammu yang enak." },
        { name: "Nasi Jinggo", meaning: "Kamu selalu bikin kenyang dan puas dengan porsi kecilmu yang enak." },
        { name: "Lumpia Semarang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Sate Lilit", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Bakpia Pathok", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa manismu yang enak." },
        { name: "Sate Maranggi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Nasi Kapau", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Es Pisang Ijo", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Nasi Tempong", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
        { name: "Keripik Tempe", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Bakso Malang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang lezat." },
        { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Es Cincau", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Nasi Bogana", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Tempe Mendoan", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Pecel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Es Oyen", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Bolu Kukus", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa manismu yang enak." },
        { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Bika Ambon", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa manismu yang enak." },
        { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Ayam Betutu", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Lemper", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Tempong", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
        { name: "Kue Ape", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa manismu yang enak." },
        { name: "Lontong Sayur", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Kuning", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Es Teler", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Es Campur", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Nasi Kebuli", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Tumpeng", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Es Timun Serut", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Es Timun", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Soto Ayam Lamongan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Es Pisang Hijau", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Tahu Bulat", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Nasi Tutug Oncom", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Roti Bakar", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Es Dawet", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Cendol", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Bubur Sumsum", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Nasi Kucing", meaning: "Kamu selalu bikin kenyang dan puas dengan porsi kecilmu yang enak." },
        { name: "Sop Kambing", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Es Podeng", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Nasi Jagung", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Es Lilin", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Nasi Liwet", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Kuning", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Kebuli", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Es Kelapa Muda", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
        { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Nasi Jagung", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Tempong", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
        { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Rujak Cingur", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa asammu yang enak." },
        { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Nasi Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
        { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." },
        { name: "Sate Lilit", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Kucing", meaning: "Kamu selalu bikin kenyang dan puas dengan porsi kecilmu yang enak." },
        { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
        { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
        { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
        { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
        { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
        { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
        { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak."},
    { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Es Kelapa Muda", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Sayur", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Kapau", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
    { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
    { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
    { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." },
    { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Es Kelapa Muda", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Sayur", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Kapau", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
    { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
    { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
    { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." },
    { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Es Kelapa Muda", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Sayur", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Kapau", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
    { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
    { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
    { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." },
    { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Es Kelapa Muda", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Sayur", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Kapau", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
    { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
    { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
    { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." },
    { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Es Kelapa Muda", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Sayur", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Kapau", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
    { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
    { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
    { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." },
    { name: "Es Buah", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Es Kelapa Muda", meaning: "Kamu segar dan selalu bikin suasana jadi lebih adem di saat-saat panas." },
    { name: "Nasi Bebek", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Rendang Daging", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Sayur", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Bali", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Kapau", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Gandul", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Langgi", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Jamblang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Sate Taichan", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa pedasmu yang enak." },
    { name: "Ayam Goreng", meaning: "Kamu selalu bikin suasana jadi lebih hangat dan nyaman." },
    { name: "Gulai Ikan", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Soto Betawi", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Pempek Palembang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Bubur Ayam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Liwet Solo", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Nasi Timbel", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Pempek Kapal Selam", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Lontong Balap", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Soto Ayam", meaning: "Kamu selalu bikin hangat dan puas dengan kuahmu yang lezat." },
    { name: "Tahu Sumedang", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa gurihmu yang enak." },
    { name: "Ayam Taliwang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa khasmu yang enak." },
    { name: "Nasi Padang", meaning: "Kamu selalu bikin kenyang dan puas dengan rasa gurihmu yang enak." },
    { name: "Ayam Geprek", meaning: "Kamu selalu bikin suasana jadi lebih seru dengan rasa pedasmu yang enak." }
    ];

    if (nama === "") {
        Swal.fire({
            toast: true,
            icon: 'error',
            title: 'Masukkan nama Anda!',
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        });
        return;
    }

    // Cek local storage untuk melihat apakah khodam untuk nama ini sudah tersimpan
    let savedKhodam = localStorage.getItem(nama);
    if (savedKhodam) {
        savedKhodam = JSON.parse(savedKhodam);
        document.getElementById("result").innerText = `${nama}, khodam Kamu adalah ${savedKhodam.name}. (${savedKhodam.meaning})`;

        Swal.fire({
            toast: true,
            icon: 'success',
            title: 'Khodam berhasil ditemukan!',
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        });
        return;
    }

    // Jika tidak ada data di local storage, pilih khodam secara acak
    if (khodams.length === 0) {
        document.getElementById("result").innerText = `${nama}, Kamu tidak memiliki khodam.`;

        Swal.fire({
            toast: true,
            icon: 'warning',
            title: 'Maaf, tidak ada khodam yang tersedia saat ini.',
            position: 'top-end',
            showConfirmButton: false,
            timer: 3000,
            timerProgressBar: true
        });
        return;
    }

    const randomIndex = Math.floor(Math.random() * khodams.length);
    const chosenKhodam = khodams[randomIndex];

    // Simpan khodam yang dipilih ke local storage
    localStorage.setItem(nama, JSON.stringify(chosenKhodam));

    document.getElementById("result").innerText = `${nama}, khodam Kamu adalah ${chosenKhodam.name}. (${chosenKhodam.meaning})`;

    Swal.fire({
        toast: true,
        icon: 'success',
        title: 'Khodam berhasil ditemukan!',
        position: 'top-end',
        showConfirmButton: false,
        timer: 3000,
        timerProgressBar: true
    });
}